import { Rarity } from "@/types/game";

export const getRarityBorderColor = (rarity: Rarity): string => {
  switch (rarity) {
    case "COMMON":
      return "#A8A29E"; // Stone Grey: Soft, matte ash
    case "UNCOMMON":
      return "#6A9A6A"; // Sage Green: Desaturated, earthy green
    case "RARE":
      return "#5B7C99"; // Slate Blue: Cool, dusty blue
    default:
      return "transparent";
  }
};

export const getStrokeImage = (rarity: string) => {
  switch (rarity) {
    case "RARE":
      return "/assets/icons/rare_stroke.webp";
    case "UNCOMMON":
      return "/assets/icons/uncommon_stroke.webp";
    default:
      return "/assets/icons/common_stroke.webp";
  }
};

export const generateRandomPlayerName = (
  useNumbers: boolean = true,
): string => {
  const adjectives = [
    // -- Short Adjectives (Max 3 chars) --
    "Red",
    "Blu",
    "Neo",
    "Arc",
    "Zen",
    "Mad",
    "Bad",
    "Big",
    "Hot",
    "Ice",
    "Sky",
    "Sea",
    "Sun",
    "Raw",
    "Pro",
    "Top",
    "New",
    "Old",
    "Far",
    "Dim",
    "Lit",
    "Odd",
    "Key",
    "Low",
    "Dry",
    "Wet",
    "Fat",
    "Fit",
    "Pop",
    "Gem",
    "Joy",
    "Sad",
    "Toy",
    "War",
    "Win",
    "One",
    "Two",
    "Six",
    "Ten",
    "Air",
    "Ash",
    "Bio",
    "Cry",
    "Dew",
    "Ego",
    "Elf",
    "Fog",
    "God",
    "Hex",
    "Imp",
    "Ink",
    "Ion",
    "Jet",
    "Kin",
    "Law",
    "Mob",
    "Net",
    "Orb",
    "Pit",
    "Ray",
    "Sin",
    "Spy",
    "Tax",
    "Vow",
    "Web",
    "Zoo",
  ];

  const nouns = [
    // -- Short Nouns (Max 4 chars) --
    "Wolf",
    "Bear",
    "Lion",
    "King",
    "Lord",
    "Mage",
    "Bot",
    "Hero",
    "Duke",
    "Bard",
    "Monk",
    "Chef",
    "Hawk",
    "Crow",
    "Dove",
    "Duck",
    "Frog",
    "Goat",
    "Lamb",
    "Lynx",
    "Mole",
    "Moth",
    "Mule",
    "Orca",
    "Puma",
    "Seal",
    "Slug",
    "Swan",
    "Toad",
    "Wasp",
    "Worm",
    "Yeti",
    "Atom",
    "Aura",
    "Base",
    "Beam",
    "Bias",
    "Bond",
    "Bone",
    "Code",
    "Core",
    "Crew",
    "Data",
    "Disc",
    "Doom",
    "Dust",
    "Echo",
    "Edge",
    "Face",
    "Fact",
    "Fame",
    "Fear",
    "Fire",
    "Flow",
    "Flux",
    "Form",
    "Fuel",
    "Fury",
    "Gate",
    "Gear",
    "Gift",
    "Glow",
    "Gold",
    "Grid",
    "Halo",
    "Hate",
    "Helm",
    "Hope",
    "Host",
    "Icon",
    "Idea",
    "Iron",
    "Item",
    "Jade",
    "Jazz",
    "Jinx",
    "Kick",
    "Kiss",
    "Kite",
    "Knot",
    "Lava",
    "Leaf",
    "Life",
    "Link",
    "Lock",
    "Loop",
    "Luck",
    "Lure",
    "Mask",
    "Maze",
    "Menu",
    "Mesh",
    "Mist",
    "Mode",
    "Moon",
    "Myth",
    "Name",
    "Neon",
    "Node",
    "Note",
    "Nova",
    "Omen",
    "Pact",
    "Page",
    "Pain",
    "Path",
    "Peak",
    "Plan",
    "Plot",
    "Poem",
    "Poet",
    "Poll",
    "Pool",
    "Port",
    "Post",
    "Pump",
    "Punk",
    "Rage",
    "Raid",
    "Rain",
    "Rank",
    "Rate",
    "Rift",
    "Ring",
    "Risk",
    "Rock",
    "Role",
    "Root",
    "Rose",
    "Rule",
    "Rune",
    "Rush",
    "Rust",
    "Safe",
    "Sage",
    "Sail",
    "Salt",
    "Sand",
    "Scan",
    "Scar",
    "Seed",
    "Seek",
    "Self",
    "Ship",
    "Shot",
    "Show",
    "Side",
    "Sign",
    "Silk",
    "Site",
    "Size",
    "Skin",
    "Snow",
    "Soil",
    "Song",
    "Soul",
    "Span",
    "Spot",
    "Star",
    "Stem",
    "Step",
    "Stop",
    "Stud",
    "Suit",
    "Sync",
    "Tail",
    "Tale",
    "Tank",
    "Tape",
    "Task",
    "Team",
    "Tech",
    "Tent",
    "Term",
    "Test",
    "Text",
    "Tide",
    "Tile",
    "Time",
    "Tint",
    "Tone",
    "Tool",
    "Tour",
    "Town",
    "Trap",
    "Tree",
    "Trip",
    "Tube",
    "Tune",
    "Type",
    "Unit",
    "User",
    "Veil",
    "Vein",
    "Vent",
    "Verb",
    "Vest",
    "Vice",
    "View",
    "Vine",
    "Visa",
    "Void",
    "Volt",
    "Vote",
    "Wall",
    "Wand",
    "Wave",
    "Way",
    "Wind",
    "Wing",
    "Wire",
    "Wish",
    "Word",
    "Work",
    "Zone",
    "Zoom",
  ];

  // 1. Pick a random Adjective
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)];

  // 2. Pick a random Noun
  const noun = nouns[Math.floor(Math.random() * nouns.length)];

  let name = `${adj}${noun}`;

  // 3. (Optional) Add a suffix number for uniqueness (0-999)
  if (useNumbers) {
    const randomNum = Math.floor(Math.random() * 1000);
    name += randomNum.toString();
  }

  return name;
};

export function generateRandomPlayerInfo(level: number) {
  return {
    gems: 1000,
    gold: 500,
    inventory: [],
    level: level,
    experience: 0,
    name: generateRandomPlayerName(),
    tag: "#1234",
    activeProfilePicId: "default_1",
    unlockedProfilePicIds: ["default_1", "default_2"],
    battleTier: 1,
    lastSeenLevel: level,
  };
}
